services:
  postgres:
    image: postgres:17
    container_name: kzarix_db
    environment:
      POSTGRES_DB: kzarix-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kzarix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: kzarix_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ktite.m3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: