spring.application.name = Kzarix
server.port=8085
spring.datasource.url=jdbc:h2:mem:kzarix
spring.datasource.driverClassName=org.h2.Driver

spring.security.oauth2.client.registration.okta.client-id=
spring.security.oauth2.client.registration.okta.client-secret=
spring.security.oauth2.client.registration.okta.redirect-uri=
spring.security.oauth2.client.registration.okta.scope=openid,profile

spring.security.oauth2.client.provider.okta.issuer-uri=